#
# This lovely piece of code was generated by ChatGPT4 on Friday Jan 5 in about a minute
# Lets compare it to my app...lol
#


import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# Define the knowledge areas from the DAMA Wheel
knowledge_areas = [
    "Data Governance", "Data Architecture", "Data Modeling & Design",
    "Data Storage & Operations", "Data Security", "Data Integration & Interoperability",
    "Document & Content Management", "Reference & Master Data",
    "Data Warehousing & Business Intelligence", "Metadata", "Data Quality"
]

# Initialize the Streamlit app
st.title("DAMA Wheel Maturity Level Assessment")

# Create sliders for each of the 11 knowledge areas
maturity_levels = {}
for area in knowledge_areas:
    maturity_levels[area] = st.slider(f"Select your maturity level for {area}:", 0, 5, 3)

# Convert the maturity levels to a list and append the first value to close the radar chart loop
values = list(maturity_levels.values()) + [list(maturity_levels.values())[0]]

# Calculate the angle for each knowledge area
angles = [n / float(len(knowledge_areas)) * 2 * np.pi for n in range(len(knowledge_areas))]
angles += angles[:1]  # Complete the loop

# Set up the radar chart (polar plot)
fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))

# Draw the plot for the maturity levels
ax.fill(angles, values, 'teal', alpha=0.25)
ax.plot(angles, values, 'o-', linewidth=2)

# Add labels for the knowledge areas
ax.set_thetagrids(np.degrees(angles[:-1]), knowledge_areas)

# Display the radar chart in the Streamlit app
st.pyplot(fig)
